plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - ./markdown/note.md
  - ./markdown/practicals1.md
  - ./markdown/unit1.md

theme: jekyll-theme-architect
